from pathlib import Path

DEVELOPING = False

EXPENSE_CATEGORIES = [
    "SPORTS",
    "HEALTH",
    "STUDY",
    "FOOD",
    "LEISURE",
    "CLOTHES",
    "OTHERS",
    "SAVINGS",
]

SUPPORTED_CURRENCIES = [
    "BRL",
    "US",
    "EUR",
]

CURRENT_DIRECTORY_NAME = "current"
BACKUP_DIRECTORY_NAME = "backup"
DEV_DIRECTORY_NAME = "dev"

DEFAULT_CURRENCY = "BRL"
DEFAULT_DESCRIPTION = "NO DESCRIPTION"
DEFAULT_CATEGORY = "OTHERS"

INCOME_FILENAME = ".income.json"

NAME_COLUMN = "Name"
CATEGORY_COLUMN = "Category"
AMOUNT_COLUMN = "Amount"
CURRENCY_COLUMN = "Currency"
DESCRIPTION_COLUMN = "Description"
DATE_COLUMN = "Date"


PATH_TO_EXPENSE_FILES = Path("./expense_files")
PATH_TO_EXPENSE_FILES_CURRENT = PATH_TO_EXPENSE_FILES / CURRENT_DIRECTORY_NAME
PATH_TO_EXPENSE_FILES_CURRENT_BACKUP = PATH_TO_EXPENSE_FILES_CURRENT / BACKUP_DIRECTORY_NAME
PATH_TO_EXPENSE_FILES_DEV = PATH_TO_EXPENSE_FILES / DEV_DIRECTORY_NAME
PATH_TO_EXPENSE_FILES_DEV_BACKUP = PATH_TO_EXPENSE_FILES_DEV / BACKUP_DIRECTORY_NAME

PATH_TO_INCOME = Path("./")
PATH_TO_INCOME_FILE = PATH_TO_INCOME / INCOME_FILENAME
