from pathlib import Path

DEVELOPING = False

EXPENSE_CATEGORIES = [
    "SPORTS",
    "HEALTH",
    "STUDY",
    "FOOD",
    "LEISURE",
    "CLOTHES",
    "OTHERS",
    "SAVINGS",
]

SUPPORTED_CURRENCIES = [
    "BRL",
    "US",
    "EUR",
]

DEFAULT_CURRENCY = "BRL"
DEFAULT_DESCRIPTION = "NO DESCRIPTION"
DEFAULT_CATEGORY = "OTHERS"

PATH_TO_EXPENSE_FILES = Path("./expense_files")
PATH_TO_EXPENSE_FILES_CURRENT = PATH_TO_EXPENSE_FILES / "current"
PATH_TO_EXPENSE_FILES_CURRENT_BACKUP = PATH_TO_EXPENSE_FILES_CURRENT / "backup"
PATH_TO_EXPENSE_FILES_DEV = PATH_TO_EXPENSE_FILES / "dev"
PATH_TO_EXPENSE_FILES_DEV_BACKUP = PATH_TO_EXPENSE_FILES_DEV / "backup"

PATH_TO_INCOME = Path("./income")
PATH_TO_INCOME_FILE = PATH_TO_INCOME / ".income.json"

NAME_COLUMN = "Name"
CATEGORY_COLUMN = "Category"
AMOUNT_COLUMN = "Amount"
CURRENCY_COLUMN = "Currency"
DESCRIPTION_COLUMN = "Description"
DATE_COLUMN = "Date"
